#define DEFINE_COEFFICIENTS_GETTER(name) \
    std::vector<complex128> name##n; \
    double get_##name##1() const { return abs(this->name##n[0]); }; \
    double get_##name##2() const { return abs(this->name##n[1]); }; \
    double get_##name##3() const { return abs(this->name##n[2]); }; \
    complex128 get_##name##1_complex128() const { return this->name##n[0]; }; \
    complex128 get_##name##2_complex128() const { return this->name##n[1]; }; \
    complex128 get_##name##3_complex128() const { return this->name##n[2]; };

#define DEFINE_COEFFICIENTS_GETTERS_1(A) \
    DEFINE_COEFFICIENTS_GETTER(A)

#define DEFINE_COEFFICIENTS_GETTERS_2(A, B) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B)

#define DEFINE_COEFFICIENTS_GETTERS_3(A, B, C) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B) \
    DEFINE_COEFFICIENTS_GETTER(C)

#define DEFINE_COEFFICIENTS_GETTERS_4(A, B, C, D) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B) \
    DEFINE_COEFFICIENTS_GETTER(C) \
    DEFINE_COEFFICIENTS_GETTER(D)

#define DEFINE_COEFFICIENTS_GETTERS_5(A, B, C, D, E) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B) \
    DEFINE_COEFFICIENTS_GETTER(C) \
    DEFINE_COEFFICIENTS_GETTER(D) \
    DEFINE_COEFFICIENTS_GETTER(E)

#define DEFINE_COEFFICIENTS_GETTERS_6(A, B, C, D, E, F) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B) \
    DEFINE_COEFFICIENTS_GETTER(C) \
    DEFINE_COEFFICIENTS_GETTER(D) \
    DEFINE_COEFFICIENTS_GETTER(E) \
    DEFINE_COEFFICIENTS_GETTER(F)

#define DEFINE_COEFFICIENTS_GETTERS_7(A, B, C, D, E, F, G) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B) \
    DEFINE_COEFFICIENTS_GETTER(C) \
    DEFINE_COEFFICIENTS_GETTER(D) \
    DEFINE_COEFFICIENTS_GETTER(E) \
    DEFINE_COEFFICIENTS_GETTER(F) \
    DEFINE_COEFFICIENTS_GETTER(G)

#define DEFINE_COEFFICIENTS_GETTERS_8(A, B, C, D, E, F, G, H) \
    DEFINE_COEFFICIENTS_GETTER(A) \
    DEFINE_COEFFICIENTS_GETTER(B) \
    DEFINE_COEFFICIENTS_GETTER(C) \
    DEFINE_COEFFICIENTS_GETTER(D) \
    DEFINE_COEFFICIENTS_GETTER(E) \
    DEFINE_COEFFICIENTS_GETTER(F) \
    DEFINE_COEFFICIENTS_GETTER(G) \
    DEFINE_COEFFICIENTS_GETTER(H)
