# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  apt_packages:
    - cmake
    - gcc
    - gfortran
    - xvfb
    - x11-utils
    - libxkbcommon-x11-0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xinerama0
    - libxcb-xfixes0
    - xdotool

  tools:
    python: "3.11"
  jobs:
    pre_install:
      - Xvfb :99 &
      - export DISPLAY=:99
      - cd docs && rm -rf source/gallery
      - mkdir build && cd build && cmake -G "Unix Makefiles" .. && make install
      - sleep 3

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - documentation

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false



