# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martth/Desktop/git_project/gitlab/PyMieSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martth/Desktop/git_project/gitlab/PyMieSim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martth/Desktop/git_project/gitlab/PyMieSim/CMakeFiles /home/martth/Desktop/git_project/gitlab/PyMieSim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martth/Desktop/git_project/gitlab/PyMieSim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GaussianBeam

# Build rule for target.
GaussianBeam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GaussianBeam
.PHONY : GaussianBeam

# fast build rule for target.
GaussianBeam/fast:
	$(MAKE) -f CMakeFiles/GaussianBeam.dir/build.make CMakeFiles/GaussianBeam.dir/build
.PHONY : GaussianBeam/fast

#=============================================================================
# Target rules for targets named Fibonacci

# Build rule for target.
Fibonacci: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Fibonacci
.PHONY : Fibonacci

# fast build rule for target.
Fibonacci/fast:
	$(MAKE) -f CMakeFiles/Fibonacci.dir/build.make CMakeFiles/Fibonacci.dir/build
.PHONY : Fibonacci/fast

#=============================================================================
# Target rules for targets named _Scatterer

# Build rule for target.
_Scatterer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _Scatterer
.PHONY : _Scatterer

# fast build rule for target.
_Scatterer/fast:
	$(MAKE) -f CMakeFiles/_Scatterer.dir/build.make CMakeFiles/_Scatterer.dir/build
.PHONY : _Scatterer/fast

#=============================================================================
# Target rules for targets named Scatterer

# Build rule for target.
Scatterer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Scatterer
.PHONY : Scatterer

# fast build rule for target.
Scatterer/fast:
	$(MAKE) -f CMakeFiles/Scatterer.dir/build.make CMakeFiles/Scatterer.dir/build
.PHONY : Scatterer/fast

PyMieSim/FibonnaciMesh.o: PyMieSim/FibonnaciMesh.cpp.o

.PHONY : PyMieSim/FibonnaciMesh.o

# target to build an object file
PyMieSim/FibonnaciMesh.cpp.o:
	$(MAKE) -f CMakeFiles/Fibonacci.dir/build.make CMakeFiles/Fibonacci.dir/PyMieSim/FibonnaciMesh.cpp.o
.PHONY : PyMieSim/FibonnaciMesh.cpp.o

PyMieSim/FibonnaciMesh.i: PyMieSim/FibonnaciMesh.cpp.i

.PHONY : PyMieSim/FibonnaciMesh.i

# target to preprocess a source file
PyMieSim/FibonnaciMesh.cpp.i:
	$(MAKE) -f CMakeFiles/Fibonacci.dir/build.make CMakeFiles/Fibonacci.dir/PyMieSim/FibonnaciMesh.cpp.i
.PHONY : PyMieSim/FibonnaciMesh.cpp.i

PyMieSim/FibonnaciMesh.s: PyMieSim/FibonnaciMesh.cpp.s

.PHONY : PyMieSim/FibonnaciMesh.s

# target to generate assembly for a file
PyMieSim/FibonnaciMesh.cpp.s:
	$(MAKE) -f CMakeFiles/Fibonacci.dir/build.make CMakeFiles/Fibonacci.dir/PyMieSim/FibonnaciMesh.cpp.s
.PHONY : PyMieSim/FibonnaciMesh.cpp.s

PyMieSim/GLMT/cpp/GaussianBeam.o: PyMieSim/GLMT/cpp/GaussianBeam.cpp.o

.PHONY : PyMieSim/GLMT/cpp/GaussianBeam.o

# target to build an object file
PyMieSim/GLMT/cpp/GaussianBeam.cpp.o:
	$(MAKE) -f CMakeFiles/GaussianBeam.dir/build.make CMakeFiles/GaussianBeam.dir/PyMieSim/GLMT/cpp/GaussianBeam.cpp.o
.PHONY : PyMieSim/GLMT/cpp/GaussianBeam.cpp.o

PyMieSim/GLMT/cpp/GaussianBeam.i: PyMieSim/GLMT/cpp/GaussianBeam.cpp.i

.PHONY : PyMieSim/GLMT/cpp/GaussianBeam.i

# target to preprocess a source file
PyMieSim/GLMT/cpp/GaussianBeam.cpp.i:
	$(MAKE) -f CMakeFiles/GaussianBeam.dir/build.make CMakeFiles/GaussianBeam.dir/PyMieSim/GLMT/cpp/GaussianBeam.cpp.i
.PHONY : PyMieSim/GLMT/cpp/GaussianBeam.cpp.i

PyMieSim/GLMT/cpp/GaussianBeam.s: PyMieSim/GLMT/cpp/GaussianBeam.cpp.s

.PHONY : PyMieSim/GLMT/cpp/GaussianBeam.s

# target to generate assembly for a file
PyMieSim/GLMT/cpp/GaussianBeam.cpp.s:
	$(MAKE) -f CMakeFiles/GaussianBeam.dir/build.make CMakeFiles/GaussianBeam.dir/PyMieSim/GLMT/cpp/GaussianBeam.cpp.s
.PHONY : PyMieSim/GLMT/cpp/GaussianBeam.cpp.s

PyMieSim/GLMT/cpp/Interface.o: PyMieSim/GLMT/cpp/Interface.cpp.o

.PHONY : PyMieSim/GLMT/cpp/Interface.o

# target to build an object file
PyMieSim/GLMT/cpp/Interface.cpp.o:
	$(MAKE) -f CMakeFiles/_Scatterer.dir/build.make CMakeFiles/_Scatterer.dir/PyMieSim/GLMT/cpp/Interface.cpp.o
.PHONY : PyMieSim/GLMT/cpp/Interface.cpp.o

PyMieSim/GLMT/cpp/Interface.i: PyMieSim/GLMT/cpp/Interface.cpp.i

.PHONY : PyMieSim/GLMT/cpp/Interface.i

# target to preprocess a source file
PyMieSim/GLMT/cpp/Interface.cpp.i:
	$(MAKE) -f CMakeFiles/_Scatterer.dir/build.make CMakeFiles/_Scatterer.dir/PyMieSim/GLMT/cpp/Interface.cpp.i
.PHONY : PyMieSim/GLMT/cpp/Interface.cpp.i

PyMieSim/GLMT/cpp/Interface.s: PyMieSim/GLMT/cpp/Interface.cpp.s

.PHONY : PyMieSim/GLMT/cpp/Interface.s

# target to generate assembly for a file
PyMieSim/GLMT/cpp/Interface.cpp.s:
	$(MAKE) -f CMakeFiles/_Scatterer.dir/build.make CMakeFiles/_Scatterer.dir/PyMieSim/GLMT/cpp/Interface.cpp.s
.PHONY : PyMieSim/GLMT/cpp/Interface.cpp.s

PyMieSim/LMT/cpp/interface.o: PyMieSim/LMT/cpp/interface.cpp.o

.PHONY : PyMieSim/LMT/cpp/interface.o

# target to build an object file
PyMieSim/LMT/cpp/interface.cpp.o:
	$(MAKE) -f CMakeFiles/Scatterer.dir/build.make CMakeFiles/Scatterer.dir/PyMieSim/LMT/cpp/interface.cpp.o
.PHONY : PyMieSim/LMT/cpp/interface.cpp.o

PyMieSim/LMT/cpp/interface.i: PyMieSim/LMT/cpp/interface.cpp.i

.PHONY : PyMieSim/LMT/cpp/interface.i

# target to preprocess a source file
PyMieSim/LMT/cpp/interface.cpp.i:
	$(MAKE) -f CMakeFiles/Scatterer.dir/build.make CMakeFiles/Scatterer.dir/PyMieSim/LMT/cpp/interface.cpp.i
.PHONY : PyMieSim/LMT/cpp/interface.cpp.i

PyMieSim/LMT/cpp/interface.s: PyMieSim/LMT/cpp/interface.cpp.s

.PHONY : PyMieSim/LMT/cpp/interface.s

# target to generate assembly for a file
PyMieSim/LMT/cpp/interface.cpp.s:
	$(MAKE) -f CMakeFiles/Scatterer.dir/build.make CMakeFiles/Scatterer.dir/PyMieSim/LMT/cpp/interface.cpp.s
.PHONY : PyMieSim/LMT/cpp/interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... GaussianBeam"
	@echo "... edit_cache"
	@echo "... Fibonacci"
	@echo "... _Scatterer"
	@echo "... Scatterer"
	@echo "... PyMieSim/FibonnaciMesh.o"
	@echo "... PyMieSim/FibonnaciMesh.i"
	@echo "... PyMieSim/FibonnaciMesh.s"
	@echo "... PyMieSim/GLMT/cpp/GaussianBeam.o"
	@echo "... PyMieSim/GLMT/cpp/GaussianBeam.i"
	@echo "... PyMieSim/GLMT/cpp/GaussianBeam.s"
	@echo "... PyMieSim/GLMT/cpp/Interface.o"
	@echo "... PyMieSim/GLMT/cpp/Interface.i"
	@echo "... PyMieSim/GLMT/cpp/Interface.s"
	@echo "... PyMieSim/LMT/cpp/interface.o"
	@echo "... PyMieSim/LMT/cpp/interface.i"
	@echo "... PyMieSim/LMT/cpp/interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system



# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).

html:
	$(SPHINXBUILD) -b html "docs/$(SOURCEDIR)" "docs/$(BUILDDIR)" $(SPHINXOPTS)

readDoc:
	google-chrome docs/build/index.html

cleanDoc:
	rm -rf docs/build/*
