package:
  name: pymiesim
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  number: 0
  script_env:
    - FC=ifx   # [win]
    - F90=ifx  # [win]

  script: |
    @echo on  # [win]

    rem Tools from conda build env  # [win]
    set "IFX_EXE=%BUILD_PREFIX%\Library\bin\ifx.exe"  # [win]
    set "NINJA_EXE=%BUILD_PREFIX%\Library\bin\ninja.exe"  # [win]

    if not exist "%IFX_EXE%" ( echo ifx not found & dir /b "%BUILD_PREFIX%\Library\bin" & exit /b 1 )  # [win]
    if not exist "%NINJA_EXE%" ( echo ninja not found & dir /b "%BUILD_PREFIX%\Library\bin" & exit /b 1 )  # [win]

    set "PATH=%BUILD_PREFIX%\Library\bin;%PATH%"  # [win]
    "%IFX_EXE%" --version || exit /b 1  # [win]
    "%NINJA_EXE%" --version || exit /b 1  # [win]

    rem Locate MSVC cl.exe explicitly using vswhere  # [win]
    set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"  # [win]
    if not exist "%VSWHERE%" ( echo vswhere not found at "%VSWHERE%" & exit /b 1 )  # [win]

    for /f "usebackq delims=" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find VC\Tools\MSVC\**\bin\Hostx64\x64\cl.exe`) do set "CL_EXE=%%I"  # [win]
    if not defined CL_EXE ( echo cl.exe not found via vswhere & "%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 & exit /b 1 )  # [win]

    rem Make sure link.exe is on PATH as well by adding the cl.exe directory  # [win]
    for %%D in ("%CL_EXE%") do set "MSVC_BIN_DIR=%%~dpD"  # [win]
    set "PATH=%MSVC_BIN_DIR%;%PATH%"  # [win]

    where cl.exe  # [win]
    where link.exe  # [win]
    cl.exe /Bv  # [win]

    rem Convert paths to CMake friendly forward slashes  # [win]
    set "IFX_EXE_CMAKE=%IFX_EXE:\=/%"  # [win]
    set "NINJA_EXE_CMAKE=%NINJA_EXE:\=/%"  # [win]
    set "CL_EXE_CMAKE=%CL_EXE:\=/%"  # [win]

    rem Force Ninja and pin all compilers explicitly  # [win]
    "%PYTHON%" -m pip install . -vv --no-deps --no-build-isolation ^  # [win]
      --config-settings=cmake.args=-GNinja;-DCMAKE_MAKE_PROGRAM:FILEPATH=%NINJA_EXE_CMAKE%;-DCMAKE_C_COMPILER:FILEPATH=%CL_EXE_CMAKE%;-DCMAKE_CXX_COMPILER:FILEPATH=%CL_EXE_CMAKE%;-DCMAKE_Fortran_COMPILER:FILEPATH=%IFX_EXE_CMAKE% ^  # [win]
      || exit /b 1  # [win]




requirements:
  build:
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}   # [unix]
    - ifx_win-64                  # [win]
    - ifx_impl_win-64             # [win]
  host:
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - python {{PY_VER}}*
    - martinpdes::pyoptik
    - martinpdes::mpsplots
    - martinpdes::typedunit
    - matplotlib ~=3.10.3
    - numpy ==2.2.6
    - pydantic ~=2.9.2
    - pandas ~=2.3.0
    - pint-pandas ~=0.6
    - tabulate ~=0.9
    - pyvista ==0.44.2

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://martinpdes.github.io/PyMieSim/
  license_file: LICENSE
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

files:
  include:
    - "PyMieSim/binary/*.so"

test:
  imports:
    - PyMieSim
  requires:
    - python {{ PY_VER }}*
    - python_abi 3.13.* *_cp313   # [py==313]
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ==1.5
    - coverage ==7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
