package:
  name: pymiesim
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  number: 0
  script_env:
    - CMAKE_GENERATOR=Ninja
    - FC=ifx   # [win]
    - F90=ifx  # [win]
build:
  number: 0

  script_env:
    - CMAKE_GENERATOR=Ninja
    - FC=ifx   # [win]
    - F90=ifx  # [win]

  script: |
    :: Windows  # [win]
    @echo on  # [win]

    set "IFX_EXE=%BUILD_PREFIX%\Library\bin\ifx.exe"  # [win]
    if not exist "%IFX_EXE%" (  # [win]
      echo ifx.exe not found at "%IFX_EXE%"  # [win]
      dir /b "%BUILD_PREFIX%\Library\bin"  # [win]
      exit /b 1  # [win]
    )  # [win]

    set "PATH=%BUILD_PREFIX%\Library\bin;%PATH%"  # [win]
    "%IFX_EXE%" --version || exit /b 1  # [win]

    set "IFX_EXE_CMAKE=%IFX_EXE:\=/%"  # [win]
    set "SKBUILD_CMAKE_ARGS=-DCMAKE_Fortran_COMPILER:FILEPATH=%IFX_EXE_CMAKE%"  # [win]

    "%PYTHON%" -m pip install . -vv --no-deps --no-build-isolation || exit /b 1  # [win]

    # Unix (Linux and macOS)  # [unix]
    export CMAKE_GENERATOR=Ninja  # [unix]
    export FC="${FC:-gfortran}"  # [unix]
    export F90="${F90:-gfortran}"  # [unix]
    "${FC}" --version  # [unix]
    export SKBUILD_CMAKE_ARGS="${SKBUILD_CMAKE_ARGS:-} -DCMAKE_Fortran_COMPILER=${FC}"  # [unix]
    "${PYTHON}" -m pip install . -vv --no-deps --no-build-isolation  # [unix]

requirements:
  build:
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}   # [unix]
    - ifx_win-64                  # [win]
    - ifx_impl_win-64             # [win]
  host:
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - python {{PY_VER}}*
    - martinpdes::pyoptik
    - martinpdes::mpsplots
    - martinpdes::typedunit
    - matplotlib ~=3.10.3
    - numpy ==2.2.6
    - pydantic ~=2.9.2
    - pandas ~=2.3.0
    - pint-pandas ~=0.6
    - tabulate ~=0.9
    - pyvista ==0.44.2

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://martinpdes.github.io/PyMieSim/
  license_file: LICENSE
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

files:
  include:
    - "PyMieSim/binary/*.so"

test:
  imports:
    - PyMieSim
  requires:
    - python {{ PY_VER }}*
    - python_abi 3.13.* *_cp313   # [py==313]
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ==1.5
    - coverage ==7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
