package:
  name: pymiesim
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - python {{PY_VER}}*
    - flexparser <0.4  # This is due to a dataclass inheritance problem coming from the pint package
    - martinpdes::pyoptik
    - numpy ==2.2.6
    - mpsplots ==1.6.3
    - pydantic ~=2.9.2
    - pandas ~=2.3.0
    - pint-pandas ~=0.6
    - tabulate ~=0.9
    - pyvista ==0.44.2

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://martinpdes.github.io/PyMieSim/
  license_file: LICENSE
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

files:
  include:
    - "PyMieSim/binary/*.so"

test:
  imports:
    - PyMieSim
  requires:
    - python {{PY_VER}}*
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ~=1.5.0
    - coverage ~=7.6.1
  commands:
    - python -m pytest --ignore=tests/gui
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS