package:
  name: pymiesim
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  number: 0
  script: |
    @echo on  # [win]
    "%PYTHON%" -m pip install . -vv --no-deps --no-build-isolation ^  # [win]
      "--config-settings=cmake.args=-GNinja;-DCMAKE_Fortran_COMPILER=flang;-DCMAKE_LINKER=link;-DCMAKE_RC_COMPILER=rc;-DCMAKE_MT=mt" ^  # [win]
      || exit /b 1  # [win]

    "${PYTHON}" -m pip install . -vv --no-deps --no-build-isolation  # [unix]


requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - vs2022_win-64          # [win]
    - flang_win-64           # [win]
    - ninja
    - cmake
    - "{{ compiler('fortran') }}"  # [unix]
  host:
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - python {{PY_VER}}*
    - martinpdes::pyoptik
    - martinpdes::mpsplots
    - martinpdes::typedunit
    - matplotlib ~=3.10.3
    - numpy ==2.2.6
    - pydantic ~=2.9.2
    - pandas ~=2.3.0
    - pint-pandas ~=0.6
    - tabulate ~=0.9
    - pyvista ==0.44.2

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://martinpdes.github.io/PyMieSim/
  license_file: LICENSE
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

files:
  include:
    - "PyMieSim/binary/*.so"

test:
  imports:
    - PyMieSim
  requires:
    - python {{ PY_VER }}*
    - python_abi 3.13.* *_cp313   # [py==313]
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ==1.5
    - coverage ==7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
