package:
  name: pymiesim
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  number: 0
  script_env:
    - CMAKE_GENERATOR=Ninja
    - FC=ifx   # [win]
    - F90=ifx  # [win]
  script: |
    :: ---------------- Windows only ----------------  # [win]
    @echo on  # [win]

    :: Use conda-build's Library/bin on Windows  # [win]
    set "PATH=%LIBRARY_BIN%;%PATH%"  # [win]

    if not exist "%LIBRARY_BIN%\ifx.exe" (  # [win]
      echo ifx.exe not found in %LIBRARY_BIN%  # [win]
      dir /b "%LIBRARY_BIN%"  # [win]
      exit /b 1  # [win]
    )  # [win]

    "%LIBRARY_BIN%\ifx.exe" --version || exit /b 1  # [win]

    :: Smoke test: can ifx compile + link at all in this env?  # [win]
    echo program hello> conda_ifx_smoketest.f90  # [win]
    echo print *, "hello">> conda_ifx_smoketest.f90  # [win]
    echo end program hello>> conda_ifx_smoketest.f90  # [win]
    "%LIBRARY_BIN%\ifx.exe" conda_ifx_smoketest.f90 /Fe:conda_ifx_smoketest.exe || exit /b 1  # [win]

    :: Pass compiler to CMake in a Windows safe way (forward slashes)  # [win]
    set "IFX_EXE_CMAKE=%LIBRARY_BIN:\=/%/ifx.exe"  # [win]
    set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_Fortran_COMPILER:FILEPATH=%IFX_EXE_CMAKE%"  # [win]
    set "SKBUILD_CMAKE_ARGS=%CMAKE_ARGS%"  # [win]

    "%PYTHON%" -m pip install . -vv --no-deps --no-build-isolation || exit /b 1  # [win]

    # ---------------- Unix only (Linux + macOS) ----------------  # [unix]
    export CMAKE_GENERATOR=Ninja  # [unix]
    export FC="${FC:-gfortran}"  # [unix]
    "${FC}" --version  # [unix]
    export CMAKE_ARGS="${CMAKE_ARGS:-} -DCMAKE_Fortran_COMPILER=${FC}"  # [unix]
    export SKBUILD_CMAKE_ARGS="${SKBUILD_CMAKE_ARGS:-} -DCMAKE_Fortran_COMPILER=${FC}"  # [unix]
    "${PYTHON}" -m pip install . -vv --no-deps --no-build-isolation  # [unix]

requirements:
  build:
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}   # [unix]
    - ifx_win-64                  # [win]
    - ifx_impl_win-64             # [win]
  host:
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - python {{PY_VER}}*
    - martinpdes::pyoptik
    - martinpdes::mpsplots
    - martinpdes::typedunit
    - matplotlib ~=3.10.3
    - numpy ==2.2.6
    - pydantic ~=2.9.2
    - pandas ~=2.3.0
    - pint-pandas ~=0.6
    - tabulate ~=0.9
    - pyvista ==0.44.2

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://martinpdes.github.io/PyMieSim/
  license_file: LICENSE
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

files:
  include:
    - "PyMieSim/binary/*.so"

test:
  imports:
    - FlowCyPy
  requires:
    - python {{ PY_VER }}*
    - python_abi 3.13.* *_cp313   # [py==313]
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ==1.5
    - coverage ==7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
