"""Type interface for native single-scatterer setup operations."""
from typing import overload
from pint import Quantity
from matplotlib.figure import Figure
from .scatterer import BaseScatterer
from .source import BaseSource
from .detector import BaseDetector
from ..mesh import FullMesh
from .representations import FarFields, Stokes, SPF, S1S2, NearFields, Footprint

class Setup:
    def __init__(self, scatterer: BaseScatterer, source: BaseSource, detector: BaseDetector | None = ..., debug_mode: bool = ...) -> None: ...
    @property
    def scatterer(self) -> BaseScatterer: ...
    @property
    def source(self) -> BaseSource: ...
    @property
    def detector(self) -> BaseDetector | None: ...
    def get(self, data: str) -> Quantity: ...
    def get_s1s2(self, angles: Quantity) -> tuple[Quantity, Quantity]: ...
    @overload
    def get_farfields(self, sampling: int, distance: Quantity) -> tuple[Quantity, Quantity, FullMesh]: ...
    @overload
    def get_farfields(self, phi: Quantity, theta: Quantity, distance: Quantity) -> tuple[Quantity, Quantity]: ...
    @overload
    def get_stokes(self, sampling: int, distance: Quantity) -> tuple[Quantity, Quantity, Quantity, Quantity, FullMesh]: ...
    @overload
    def get_stokes(self, phi: Quantity, theta: Quantity, distance: Quantity) -> tuple[Quantity, Quantity, Quantity, Quantity]: ...
    @overload
    def get_spf(self, sampling: int, distance: Quantity = ...) -> tuple[Quantity, FullMesh]: ...
    @overload
    def get_spf(self, phi: Quantity, theta: Quantity, distance: Quantity = ...) -> Quantity: ...
    def get_incident_nearfields(self, x: Quantity, y: Quantity, z: Quantity, field_type: str) -> Quantity: ...
    def get_scattered_nearfields(self, x: Quantity, y: Quantity, z: Quantity, field_type: str) -> Quantity: ...
    def get_total_nearfields(self, x: Quantity, y: Quantity, z: Quantity, field_type: str) -> Quantity: ...
    def get_representation(self, representation_type: str, **kwargs: object) -> FarFields | Stokes | SPF | S1S2 | NearFields | Footprint: ...
    def plot_system(self, show_axes: bool = ..., show_colorbar: bool = ..., show_detector_cone: bool = ..., show_unit_sphere: bool = ..., figure_size: float = ...) -> Figure: ...
    def __repr__(self) -> str: ...
