# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = '2.5.11.6.post1.dev0+g2cbe7056.d20241103'
__version_tuple__ = version_tuple = (2, 5, 11, 6, 'dev0', 'g2cbe7056.d20241103')
