"""Type interface for the native labeled-array binding."""
from typing import Any, Sequence, overload
import numpy as np
from numpy.typing import ArrayLike, NDArray
from matplotlib.axes import Axes
from matplotlib.artist import Artist
from pandas import DataFrame

class LabeledArray:
    def __init__(self, values: ArrayLike, dims: Sequence[str], coords: dict[str, NDArray] = ..., attrs: dict[str, Any] = ..., name: str | None = ...) -> None: ...
    @property
    def values(self) -> NDArray: ...
    @property
    def dims(self) -> tuple[str, ...]: ...
    @property
    def coords(self) -> dict[str, NDArray]: ...
    @property
    def attrs(self) -> dict[str, Any]: ...
    @property
    def name(self) -> str | None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    def to_numpy(self) -> NDArray: ...
    def as_numpy(self) -> NDArray: ...
    def as_dataframe(self) -> DataFrame: ...
    def isel(self, indexers: dict[str, int | slice]) -> LabeledArray: ...
    @overload
    def mean(self, dim: None = ..., x: None = ...) -> np.number: ...
    @overload
    def mean(self, dim: str, x: None = ...) -> LabeledArray: ...
    @overload
    def mean(self, dim: None = ..., *, x: str) -> LabeledArray: ...
    def plot(self, x: str | None = ..., y: str | None = ..., ax: Axes | None = ..., cmap: str = ..., std: str | None = ..., alpha: float = ..., legend: bool = ..., show: bool = ...) -> list[Artist]: ...
    def __repr__(self) -> str: ...
