# Simple workflow for deploying static content to GitHub Pages
name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - "*"

  pull_request:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ManyLinux_x86_64:
    if: github.event_name == 'push'
    uses: MartinPdeS/MPSActions/.github/workflows/publish_documentation.yml@master
    with:
      python-version: "3.11"
      package-name: "PyMieSim"
      apt-package: xvfb jq