# Simple workflow for deploying static content to GitHub Pages
name: Documentation

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]

  pull_request:
    branches:
      - master

concurrency:
  group: documentation-build-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ManyLinux_x86_64:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_documentation.yml@v2
    with:
      python-version: "3.11"
      package-name: "PyMieSim"
      apt-package: xvfb jq
      deploy-pages: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) }}
